- name: Restart node-exporter
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true

- name: Restart node-exporter-apt
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter-apt
    state: restarted
    daemon_reload: true
