- name: Add apt repository keys
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/trusted.gpg.d/grafana.asc
    owner: root
    group: root
    mode: '0644'

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/grafana.asc] https://apt.grafana.com stable main
    filename: grafana
    update_cache: true
    state: present

- name: Install Promtail
  ansible.builtin.apt:
    name: promtail
    state: present
