- name: Check that the /usr/bin/as exists
  ansible.builtin.stat:
    path: /usr/bin/as
  register: lynis_hardening_stat_result

- name: /usr/bin/as
  ansible.builtin.file:
    path: "/usr/bin/as"
    state: file
    mode: "0700"
  when: lynis_hardening_stat_result.stat.exists
