- name: List cron directories
  register: lynis_hardening_cron_directories
  ansible.builtin.find:
    paths: /etc
    patterns: "cron.*"
    file_type: directory
    recurse: false

- name: Cron directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0700"
  loop: "{{ lynis_hardening_cron_directories.files | map(attribute='path') }}"

