- name: List cron directories
  register: lynis_hardening_cron_directories
  ansible.builtin.find:
    paths: /etc
    patterns: "^cron\\.(.*)$"
    recurse: false

- name: Debug
  debug:
    var: lynis_hardening_cron_directories

- name: Cron directories
  ansible.builtin.file:
    path: "/etc/{{ item.path }}"
    mode: "0700"
  loop: "{{ lynis_hardening_cron_directories.files }}"

