- name: Update initamfs image
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  changed_when: true

- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 500
  throttle: 1
