- name: Add nVidia docker repository key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    keyring: /etc/apt/keyrings/nvidia-docker.key
    state: present

- name: Add nVidia docker repositories
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nvidia-docker.key] {{ item }}"
    state: present
    update_cache: false
    filename: nvidia-docker
  loop:
    - https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH)
    - https://nvidia.github.io/nvidia-container-runtime/stable/debian10/$(ARCH)
    - https://nvidia.github.io/nvidia-docker/debian10/$(ARCH)

- name: Install nVidia packages
  notify: Reboot machine
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
    state: present
    update_cache: true