- name: Add nVidia repository keys
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/{{ item }}/gpgkey
    keyring: /etc/apt/keyrings/{{ item }}.key
    state: present
  loop:
    - libnvidia-container
    - nvidia-container-runtime

- name: Add nVidia repositories
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/{{ item }}.key] https://nvidia.github.io/{{ item }}/stable/debian10/amd64 /"
    state: present
    update_cache: false
    filename: nvidia-container
  loop:
    - libnvidia-container
    - nvidia-container-runtime

- name: Install nVidia container packages
  notify: Reboot machine
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
    state: present
    update_cache: true
