- name: Install packages
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - python3-apt                   # required by apt_info.py
      - python3-prometheus-client     # required by apt_info.py
    state: present

- name: Update apt_info script with the latest version
  notify: Restart node-exporter-apt
  ansible.builtin.get_url:
    url: "{{ node_exporter_apt_info_url }}"
    dest: /usr/share/prometheus-node-exporter-collectors/apt_info.py
    owner: root
    group: root
    mode: "0755"

- name: Configure args
  notify: Restart node-exporter
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    create: false
    regex: "^ARGS=.*"
    line: "ARGS={{ node_exporter_args | default('') }}"
