- name: Install package
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure args
  register: node_exporter_config
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    create: false
    regex: "^ARGS=.*"
    line: "ARGS={{ node_exporter_args | default('') }}"

- name: Restart service
  when: node_exporter_config.changed
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true
