- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Create admin users
  ansible.builtin.include_tasks:
    file: ./admin-user.yml
  loop: "{{ users_admin_users }}"
  loop_control:
    loop_var: users_admin

- name: Configure root user
  ansible.builtin.include_tasks:
    file: ./root-user.yml
