- name: Define Docker daemon options
  ansible.builtin.set_fact:
    docker_daemon_options:
      log-driver: json-file
      log-opts:
        max-size: "{{ docker_logs_max_size }}"
        max-file: "{{ docker_logs_max_files }}"

- name: Enable access to Docker daemon over TCP
  when: docker_enable_tcp
  ansible.builtin.set_fact:
    docker_daemon_options: "{{ docker_daemon_options | combine(docker_daemon_options_tcp) }}"

- name: Define Docker daemon options for nvidia runtime
  when: docker_enable_nvidia_runtime
  ansible.builtin.set_fact:
    docker_daemon_options: "{{ docker_daemon_options | combine(docker_daemon_options_nvidia) }}"

- name: Install nvidia container toolkit
  when: docker_enable_nvidia_runtime
  ansible.builtin.include_tasks:
    file: nvidia.yaml

- name: Install Docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_add_repo: true
    docker_packages_state: present
    docker_service_state: started
    docker_install_compose: true
    docker_compose_package_state: present
