- name: Make sure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present

- name: Download apt key
  ansible.builtin.shell:
    creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    cmd: |
      set -o pipefail
      curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  args:
    executable: /bin/bash

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)"
    filename: nvidia-container-toolkit
    update_cache: true
    state: present

- name: Install container toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
